name: Update lastest version

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  update-latest-version:
    name: Update latest version git tag
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
